name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Update version
      run: |
        VERSION=${{ github.event.release.tag_name }}
        sed -i "s/__version__ = .*/__version__ = \"$VERSION\"/" np_shared_array/__init__.py
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add np_shared_array/__init__.py
        git commit -m "Update version to $VERSION"
        git push origin main
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
